import tailwindcss from '@tailwindcss/vite'
import { readdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

function generateWidgetRegistry() {
  const widgetDir = resolve('./server/api/widget')
  const names = readdirSync(widgetDir)
    .filter(f => f.endsWith('.get.ts'))
    .map(f => f.slice(0, -'.get.ts'.length))
    .sort()

  const imports = names.map(n => `import * as $${n} from '../api/widget/${n}.get'`).join('\n')
  const widgets = names.map(n => `  '${n}': $${n}.fetch,`).join('\n')
  const metas   = names.map(n => `  '${n}': $${n}.meta,`).join('\n')

  const content = [
    '// AUTO-GENERATED by nuxt.config.ts — do not edit',
    imports,
    '',
    `export const WIDGETS = {\n${widgets}\n}`,
    '',
    `export const WIDGET_METAS = {\n${metas}\n}`,
    '',
  ].join('\n')

  writeFileSync(resolve('./server/utils/widgetRegistry.ts'), content)
}

generateWidgetRegistry()

export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },

  css: ['~/assets/css/main.css'],

  vite: {
    plugins: [tailwindcss()],
  },

  components: {
    dirs: [{ path: '~/components', pathPrefix: false }],
  },

  runtimeConfig: {
    configDir: process.env.CONFIG_DIR || './config',
    allowedHosts: process.env.ALLOWED_HOSTS || '*',
  },

  routeRules: {
    '/**': {
      headers: {
        'X-Frame-Options': 'DENY',
        'X-Content-Type-Options': 'nosniff',
        'Referrer-Policy': 'strict-origin-when-cross-origin',
        'Content-Security-Policy': "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: http: blob:; connect-src 'self' https: http:; font-src 'self' data:; frame-ancestors 'none';",
      },
    },
  },
})
