import tailwindcss from '@tailwindcss/vite'
import { readdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { getVersion } from './server/utils/version'

function parseReleaseNotes(body: string): string[] {
  const lines = body.split('\n').map(l => l.trim()).filter(Boolean)
  const bullets = lines.filter(l => /^[-*] /.test(l))
  if (bullets.length > 0)
    return bullets.map(l => l.replace(/^[-*] /, ''))
  return lines
}

async function generateChangelog() {
  const headers: Record<string, string> = {
    'User-Agent': 'home-dashboard-build',
    'Accept': 'application/vnd.github.v3+json',
  }
  if (process.env.GITHUB_TOKEN)
    headers['Authorization'] = `Bearer ${process.env.GITHUB_TOKEN}`

  let releases: Array<{ tag_name: string; body: string | null }>
  try {
    const res = await fetch('https://api.github.com/repos/woofi7/home-dashboard/releases?per_page=20', { headers })
    releases = await res.json() as typeof releases
  } catch {
    console.warn('[changelog] Failed to fetch GitHub releases, skipping generation')
    return
  }

  const entries = releases
    .filter(r => r.body?.trim())
    .map(r => `  { version: ${JSON.stringify(r.tag_name)}, notes: ${JSON.stringify(parseReleaseNotes(r.body!))} },`)

  const content = [
    '// AUTO-GENERATED by nuxt.config.ts — do not edit',
    'export type ChangelogEntry = { version: string; notes: string[] }',
    '',
    `export const CHANGELOG: ChangelogEntry[] = [\n${entries.join('\n')}\n]`,
    '',
    'export function getEntry(version: string): ChangelogEntry | undefined {',
    '  return CHANGELOG.find(e => e.version === version)',
    '}',
    '',
  ].join('\n')

  writeFileSync(resolve('./shared/changelog.ts'), content)
}

function generateWidgetRegistry() {
  const widgetDir = resolve('./server/api/widget')
  const names = readdirSync(resolve('./shared/widgetDefinitions'))
    .filter(f => f.endsWith('.ts') && f !== 'types.ts' && f !== 'index.ts')
    .map(f => f.slice(0, -3))
    .sort()

  const imports = names.map(n => `import { fetch as fetch$${n} } from '../api/widget/${n}.get'`).join('\n')
  const widgets = names.map(n => `  '${n}': fetch$${n},`).join('\n')

  const content = [
    '// AUTO-GENERATED by nuxt.config.ts — do not edit',
    imports,
    '',
    `export const WIDGETS = {\n${widgets}\n}`,
    '',
  ].join('\n')

  writeFileSync(resolve('./server/utils/widgetRegistry.ts'), content)
}

generateWidgetRegistry()
await generateChangelog()

export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },

  modules: ['@pinia/nuxt', '@vite-pwa/nuxt'],

  // Pure SPA: Nitro still serves /api/*, but no SSR/payload so the client-only
  // stores (hydrated from localStorage) render once without a flash, and the
  // app shell works offline without fetching /_payload.json.
  ssr: false,

  // The PWA manifest link + install/iOS meta are declared here (not left to the
  // vite-pwa HTML transform) because our shell is prerendered by Nitro, so the
  // module's index.html transform never runs.
  app: {
    head: {
      link: [
        { rel: 'manifest', href: '/manifest.webmanifest' },
        { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32x32.png' },
        { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' },
      ],
      meta: [
        { name: 'theme-color', content: '#0f1117' },
        { name: 'mobile-web-app-capable', content: 'yes' },
        { name: 'apple-mobile-web-app-capable', content: 'yes' },
        { name: 'apple-mobile-web-app-status-bar-style', content: 'black' },
        { name: 'apple-mobile-web-app-title', content: 'Dashboard' },
      ],
    },
  },

  css: ['~/assets/css/main.css'],

  // Emit a static index.html SPA shell so the PWA can precache it and serve
  // navigations offline (navigateFallback '/').
  nitro: {
    prerender: {
      routes: ['/'],
    },
  },

  pwa: {
    registerType: 'autoUpdate',
    manifest: {
      id: '/',
      name: 'Dashboard',
      short_name: 'Dashboard',
      description: 'Self-hosted personal dashboard',
      theme_color: '#0f1117',
      background_color: '#0f1117',
      display: 'standalone',
      start_url: '/',
      icons: [
        { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
        { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
        { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
        { src: 'maskable-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      ],
    },
    workbox: {
      navigateFallback: '/',
      navigateFallbackDenylist: [/^\/api\//],
      globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
      runtimeCaching: [
        {
          // Reachability probe must always hit the network so offline is detected.
          urlPattern: ({ url }: { url: URL }) => url.pathname === '/api/healthcheck',
          handler: 'NetworkOnly',
        },
        {
          urlPattern: ({ url }: { url: URL }) => url.pathname.startsWith('/api/'),
          handler: 'NetworkFirst',
          options: {
            cacheName: 'api-cache',
            networkTimeoutSeconds: 2,
            expiration: { maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 * 7 },
            cacheableResponse: { statuses: [0, 200] },
          },
        },
      ],
    },
    client: {
      installPrompt: true,
    },
  },

  vite: {
    plugins: [tailwindcss()],
    optimizeDeps: {
      include: [
        '@fortawesome/fontawesome-svg-core',
        '@fortawesome/free-solid-svg-icons',
        '@fortawesome/vue-fontawesome',
        '@vueuse/core',
        'vue-draggable-plus',
      ],
    },
  },

  components: {
    dirs: [{ path: '~/components', pathPrefix: false }],
  },

  runtimeConfig: {
    configDir: process.env.CONFIG_DIR || './config',
    allowedHosts: process.env.ALLOWED_HOSTS || '*',
    public: {
      version: getVersion(),
    },
  },

  routeRules: {
    '/**': {
      headers: {
        'X-Frame-Options': 'DENY',
        'X-Content-Type-Options': 'nosniff',
        'Referrer-Policy': 'strict-origin-when-cross-origin',
        // Note: 'unsafe-inline' is kept for script-src because Nuxt injects an
        // inline hydration payload; removing it needs a nonce/hash setup.
        // 'unsafe-eval' is dropped — the production build does not need it.
        'Content-Security-Policy': "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: http: blob:; connect-src 'self' https: http:; font-src 'self' data:; frame-ancestors 'none';",
      },
    },
  },
})
