import tailwindcss from '@tailwindcss/vite'
import { readdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

function generateWidgetRegistry() {
  const widgetDir = resolve('./server/api/widget')
  const names = readdirSync(resolve('./shared/widgetDefinitions'))
    .filter(f => f.endsWith('.ts') && f !== 'types.ts' && f !== 'index.ts')
    .map(f => f.slice(0, -3))
    .sort()

  const imports = names.map(n => `import { fetch as fetch$${n} } from '../api/widget/${n}.get'`).join('\n')
  const widgets = names.map(n => `  '${n}': fetch$${n},`).join('\n')

  const content = [
    '// AUTO-GENERATED by nuxt.config.ts — do not edit',
    imports,
    '',
    `export const WIDGETS = {\n${widgets}\n}`,
    '',
  ].join('\n')

  writeFileSync(resolve('./server/utils/widgetRegistry.ts'), content)
}

generateWidgetRegistry()

export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },

  css: ['~/assets/css/main.css'],

  vite: {
    plugins: [tailwindcss()],
    optimizeDeps: {
      include: [
        '@fortawesome/fontawesome-svg-core',
        '@fortawesome/free-solid-svg-icons',
        '@fortawesome/vue-fontawesome',
        '@vueuse/core',
        'vue-draggable-plus',
      ],
    },
  },

  components: {
    dirs: [{ path: '~/components', pathPrefix: false }],
  },

  runtimeConfig: {
    configDir: process.env.CONFIG_DIR || './config',
    allowedHosts: process.env.ALLOWED_HOSTS || '*',
  },

  routeRules: {
    '/**': {
      headers: {
        'X-Frame-Options': 'DENY',
        'X-Content-Type-Options': 'nosniff',
        'Referrer-Policy': 'strict-origin-when-cross-origin',
        'Content-Security-Policy': "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: http: blob:; connect-src 'self' https: http:; font-src 'self' data:; frame-ancestors 'none';",
      },
    },
  },
})
